language: python
python:
  - "3.6.7"

  
# install dependencies
install:
  - pip install -r requirements.txt
  


# run pytest
script:
  - pytest 

# then post the results to coveralls
after_success:
  - coveralls
